# vim:ft=kitty

## name:     Catppuccin Cocoa
## author:   t1m-l (https://github.com/t1m-l)
## original catppuccin author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: _
## blurb:    _



# The basic colors
foreground              #DAD8D8
background              #202020
selection_foreground    #202020
selection_background    #EAD7DA

# Cursor colors
cursor                  #EAD7DA
cursor_text_color       #202020

# URL underline color when hovering with mouse
url_color               #EAD7DA

# Kitty window border colors
active_border_color     #9C9DC9
inactive_border_color   #606060
bell_border_color       #EAD28A

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #050505
active_tab_background   #D985E0
inactive_tab_foreground #DAD8D8
inactive_tab_background #101010
tab_bar_background      #050505

# Colors for marks (marked text in the terminal)
mark1_foreground #202020
mark1_background #9C9DC9
mark2_foreground #202020
mark2_background #D985E0
mark3_foreground #202020
mark3_background #67B2E4

# The 16 terminal colors

# black
color0 #FFFFFF
color8 #505050

# red
color1 #DB7072
color9 #DB7072

# green
color2  #74B96E
color10 #74B96E

# yellow
color3  #EAD28A
color11 #EAD28A

# blue
color4  #668DCC
color12 #668DCC

# magenta
color5  #EFB3D1
color13 #EFB3D1

# cyan
color6  #89CDC0
color14 #89CDC0

# white
color7  #FFFFFF
color15 #F9F9F9
