# vim:ft=kitty

## name:     Summer Paper Sunset
## author:   t1m-l (https://github.com/t1m-l)
## original catppuccin author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: _
## blurb:    _



# The basic colors
foreground              #2B2622
background              #FDFDFC
selection_foreground    #FDFDFC
selection_background    #81B4E4

# Cursor colors
cursor                  #62A9E9
cursor_text_color       #FDFDFC

# URL underline color when hovering with mouse
url_color               #3070E8

# Kitty window border colors
active_border_color     #685CD6
inactive_border_color   #C2A9A3
bell_border_color       #F49106

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #FCF2CF
active_tab_background   #E085C0
inactive_tab_foreground #E085C0
inactive_tab_background #FEF9E7
tab_bar_background      #FCF2CF

# Colors for marks (marked text in the terminal)
mark1_foreground #FDFDFC
mark1_background #685CD6
mark2_foreground #FDFDFC
mark2_background #E085C0
mark3_foreground #FDFDFC
mark3_background #62A9E9

# The 16 terminal colors

# black
# Colors from Catppuccin Cocoa
color0 #766660
color8 #91827E

# red
color1 #F53D46
color9 #F53D46

# green
color2 #369900
color10 #369900

# yellow
color3  #F49106
color11 #F49106

# blue
color4  #3070E8
color12 #3070E8

# magenta
color5  #FD9C9B
color13 #FD9C9B

# cyan
color6  #2EB8B2
color14 #2EB8B2

# white
color7  #FEF9E7
color15 #FCF2CF
