name: "stable-diffusion"

services:
  comfyui:
    image: "backbone-comfyui:latest"
    build:
      context: "."
      dockerfile: "comfyui.Containerfile"
      args:
        COMFYUI_IMAGE_TAG: "${COMFYUI_IMAGE_TAG}"
        COMFYUI_CONTAINER_PORT: "${COMFYUI_CONTAINER_PORT:-80}"
    container_name: "stable-diffusion-comfyui"
    user: "comfy"
    environment:
      COMFYUI_FRONTEND_VERSION: "${COMFYUI_FRONTEND_VERSION}"
    ports:
      - "${COMFYUI_HOST_PORT}:${COMFYUI_CONTAINER_PORT:-80}"
    volumes:
      - "./comfyui-persistence/models:/opt/ComfyUI/models"
      - "./comfyui-persistence/input:/opt/ComfyUI/input"
      - "./comfyui-persistence/output:/opt/ComfyUI/output"
      - "./comfyui-persistence/user:/opt/ComfyUI/user"
      - "./comfyui-persistence/custom_nodes:/opt/ComfyUI/custom_nodes"
    restart: "unless-stopped"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - "compute"
                - "utility"
              driver: "nvidia"
              count: "all"
